spring:
  application:
    name: springboot-mybatis-quickstart
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tlias
    username: root
    password: Zdx08080.
    driver-class-name: com.mysql.cj.jdbc.Driver
  server:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapUnderscoreToCamelCase: true
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    org .springframework.jdbc.support.JdbcTransactionManager: debug

aliyun:
  oss:
    endpoint: https://oss-cn-fuzhou.aliyuncs.com
    bucketName: lianci-java
    region: cn-fuzhou